import Head from "next/head";
import Header from "../components/shared/Header/Header";
import Hero from "../components/shared/Hero/Hero";

import styles from "../styles/pages/Collaborators.module.scss";
import { useState } from "react";
import Collaborator from "../components/Collaborators/Collaborator";

import BigArrow from "../assets/icons/bigArrow.svg";
import Link from "next/link";
import Footer from "../components/shared/Footer/Footer";
import Image from "next/image";

const collaborators = [
  {
    name: "Fnac",
    field: "Produits culturels & Tech",
    logo: "/images/collaborators/fnac.svg",
    description:
      "La Fnac est une chaîne de magasins française 🇫🇷 spécialisée dans la distribution de produits culturels (musique, littérature, cinéma, jeu vidéo) et électroniques",
    advantages: [
      "-5% sur les produits culturels avec le code LUCKYFOX2023",
      "La carte Fnac+ à moitié prix sur présentation de ta carte étudiante",
    ],
  },
  {
    name: "Uber Eats",
    field: "Restauration et Alimentation",
    logo: "/images/collaborators/uberEats.svg",
    description:
      "Trouvez les meilleurs restaurants qui livrent des repas à domicile. Faites-vous livrer sans contact vos plats préférés, vos courses et bien plus encore !",
    advantages: [
      "15€ offerts sur ta première livraison avec le code LUCKYFOX2023",
    ],
  },
  {
    name: "Fanta",
    field: "Boissons",
    logo: "/images/collaborators/fanta.svg",
    description:
      "Fun et décalée, Fanta est la boisson pétillante au goût fruité qui met une touche de fraîcheur et de couleur dans le quotidien de chacun.",
    advantages: [
      "Une canette de fanta gratuite par personne sur nos events 😉",
    ],
  },
];

const Collaborators = () => {
  const [selected, setSelected] = useState(null);

  // Si bug remplacer les 149.202.52.100 par localhost

  return (
    <>
      <Head>
        <title>Lucky Fox | Partenaires</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hero title="Nos Partenaires" />

      <main className="main">
        <section className="section dark">
          <div className="sectionContent">
            <h2 className="sectionTitle">Pourquoi des partenariats ?</h2>
            <p className="paragraph">
              Les partenariats avec des entreprises ou des assos nous permettent
              beaucoup de chose ! <br />
              Cela nous aide à trouver des fonds pour vous organiser des events
              au petits oignons ! Et la plupart des temps, nos partenaires vous
              régalent avec des offres exclusives. Tout le monde est gagnant 😁
              !
            </p>
          </div>
        </section>
        <section className="section">
          <div className={"sectionContent"}>
            <h2 className="sectionTitle">Nos partenaires</h2>
            <div className={styles.list}>
              {collaborators.map((collaborator) => (
                <div
                  className={styles.logo}
                  key={collaborator.name}
                  onClick={() => setSelected(collaborator)}
                >
                  <Image
                    unoptimized={true}
                    fill
                    title={collaborator.name}
                    src={collaborator.logo}
                    alt={collaborator.name}
                  />
                </div>
              ))}
            </div>
          </div>

          <div className={styles.contact}>
            <h2>Et peut-être vous !</h2>
            <Link href="/contact" className={styles.sectionLink}>
              <span className="sectionLink">Nous contacter</span>
              <BigArrow className={styles.arrow} />
            </Link>
          </div>
        </section>
        {selected && (
          <Collaborator
            logoURL={selected.logo}
            name={selected.name}
            field={selected.service}
            description={selected.description}
            advantages={selected.advantages}
            setCollaborator={setSelected}
          />
        )}
      </main>
      <Footer dark={true} />
    </>
  );
};

export default Collaborators;
